name: CI pipeline

on:
    push:
        branches:
            - main
            - develope
    pull_request:
        branches:
            - main
            - develope
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: [frontend, backend]
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: setup node environment
              uses: actions/setup-node@v4
              with:
                node-version: 18.x
                cache: 'npm'
                cache-dependency-path: ${{matrix.service}}/package-lock.json
            
            - name: install dependencies
              run: npm ci
              working-directory: ${{matrix.service}}
            
            - name: test
              run: npm test
              working-directory: ${{matrix.service}}
    lint:
        runs-on: ubuntu-latest
        # needs: install  
        steps:
            - name: checkout code
              uses: actions/checkout@v4        
            - name: setup node environment
              uses: actions/setup-node@v4
              with:
                node-version: 18.x
                cache: 'npm'
                cache-dependency-path: 'package-lock.json'
            - name: install dependencies
              run: npm ci 
            - name: lint code
              run: npm run lint
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: [frontend, backend]
        # needs: lint
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: setup node environment
              uses: actions/setup-node@v4
              with:
                node-version: 18.x
                cache: 'npm'
                cache-dependency-path: ${{matrix.service}}/package-lock.json
            
            - name: install dependencies
              run: npm ci
              working-directory: ${{matrix.service}}
            
            - name: build code
              run: npm run build
              working-directory: ${{matrix.service}}
        
    snyk-security:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          service: [frontend, backend]
      needs: build
      steps:
        - name: checkout code
          uses: actions/checkout@v4 
        - name: setup node environment
          uses: actions/setup-node@v4
          with:
            node-version: 18.x
            cache: 'npm'
            cache-dependency-path: 'package-lock.json'
        - name: install dependencies
          run: npm ci
          working-directory: ${{matrix.service}}
        - name: run snyk security scan
          uses: snyk/actions/node@master
          with:
            args: threshold=high --sarif-file-output=snyk.sarif
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          continue-on-error: true
        - name: run snyk SAST test on ${matrix.service}
          uses: snyk/actions/node@master
          with:
            command: snyk code test
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          continue-on-error: true 
        - name: run snyk monitor
          uses: snyk/actions/node@master
          with:
            command: monitor
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          continue-on-error: true