name: CI pipeline

on:
    push:
        branches:
            - main
            - develope
    pull_request:
        branches:
            - main
            - develope
    workflow_dispatch:

jobs:
    install:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: [frontend, backend]
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: setup node environment
              uses: actions/setup-node@v4
              with:
                node-version: 18.x
                cache: 'npm'
                cache-dependency-path: ${{matrix.service}}/package-lock.json
            
            - name: install dependencies
              run: npm ci
              working-directory: ${{matrix.service}}
            
            - name: test
              run: npm test
              working-directory: ${{matrix.service}}
    lint:
        runs-on: ubuntu-latest
        # needs: install  
        steps:
            - name: checkout code
              uses: actions/checkout@v4        
            - name: setup node environment
              uses: actions/setup-node@v4
              with:
                node-version: 18.x
                cache: 'npm'
                cache-dependency-path: 'package-lock.json'
            - name: install dependencies
              run: npm ci 
            - name: lint code
              run: npm run lint
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: [frontend, backend]
        # needs: lint
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: setup node environment
              uses: actions/setup-node@v4
              with:
                node-version: 18.x
                cache: 'npm'
                cache-dependency-path: ${{matrix.service}}/package-lock.json
            
            - name: install dependencies
              run: npm ci
              working-directory: ${{matrix.service}}
            
            - name: build code
              run: npm run build
              working-directory: ${{matrix.service}}