name: CI pipeline

on:
    push:
        branches:
            - main
            - develope
    pull_request:
        branches:
            - main
            - develope
    workflow_dispatch:

jobs:
    install:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x]
                database: [postgres, mysql]
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup node environment
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node-version}}
                cache: 'npm'
            - name: install dependencies
              run: npm ci
            - name: test
              run: npm test
    lint:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - name: lint code
              run: npm run lint
            